<?php

return [
    'gender' => [
        'No preference',
        'Male',
        'Female',
        'Other',
    ],
    'race' => [
        'No preference',
        'Asian',
        'Biracial/Multiracial',
        'Black or African American',
        'Hispanic or Latino',
        'Jewish',
        'Middle Eastern',
        'Native American or Indigenous',
        'Pacific Islander',
        'Romani',
        'White',
    ],
    'sexual_orientation' => [
        'No preference',
        'Heterosexual',
        'LGBTQ+',
    ],
    'religion' => [
        'No preference',
        'Atheism',
        'Buddhism',
        'Hinduism',
        'Islam',
        'Judaism',
        'Other',
    ],
    'language' => [
        'No preference',
        'Arabic',
        'English',
        'Hindi',
        'Mandarin Chinese',
        'Spanish',
    ],
    'modality' => [
        'No preference',
        'Individual',
        'Couple',
        'Family',
        'Group therapy',
    ],
    'orientation' => [
        'No preference',
        'Psychodynamic',
        'Cognitive',
        'Person-centred',
        'Other',
    ],
    'number_of_sessions' => [
        'No preference',
        'Fixed number of sessions',
        'Dependent on review',
        'Open-ended',
        'Other',
    ],
    'length_of_sessions' => [
        'No preference',
        'Half an hour',
        'One hour',
        'An hour and a half',
        'Two hours',
    ],
    'frequency_of_sessions' => [
        'No preference',
        'Twice weekly',
        'Weekly',
        'Monthly',
        'Ad hoc',
        'Other',
    ],
    'medication_preference' => [
        'No preference',
        'Medication',
        'Psychotherapy',
        'Both medication and psychotherapy in combination',
    ],
    'therapy_addition' => [
        'No preference',
        'Self-help books',
        'Self-help groups',
        'Computer programs',
    ],
];
